2023-08-27 20:09:44,320 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-08-27 20:09:44,322 INFO supervisord started with pid 8
2023-08-27 20:09:45,324 INFO spawned: 'nginx-unit' with pid 9
2023-08-27 20:09:45,326 INFO spawned: 'php-logs' with pid 10
2023-08-27 20:09:45,338 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:45,352 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:45,358 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:45,375 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:45,375 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:45,378 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:45,379 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:45,381 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:45,386 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:45,389 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:45,389 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:45,440 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:45,445 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:45,455 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:45,462 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:45,467 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:45,467 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:45,468 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:45,469 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:45,471 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:46,475 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:46,476 INFO success: nginx-unit entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-27 20:09:46,476 INFO success: php-logs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-27 20:09:46,484 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:46,485 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:46,491 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:46,491 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:46,492 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:46,492 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:46,510 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:46,579 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:09:46,581 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139966357645456 for <Subprocess at 139966355609936 with name nginx-unit in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:10:48,797 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-08-27 20:10:48,801 INFO supervisord started with pid 10
2023-08-27 20:10:49,803 INFO spawned: 'nginx-unit' with pid 11
2023-08-27 20:10:49,806 INFO spawned: 'php-logs' with pid 12
2023-08-27 20:10:49,810 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140510209055824 for <Subprocess at 140510219056272 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:10:49,822 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140510209055824 for <Subprocess at 140510219056272 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:10:49,823 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140510209055824 for <Subprocess at 140510219056272 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:10:49,841 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140510209055824 for <Subprocess at 140510219056272 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:10:49,842 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140510209055824 for <Subprocess at 140510219056272 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:10:49,843 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140510209055824 for <Subprocess at 140510219056272 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:10:49,844 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140510209055824 for <Subprocess at 140510219056272 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:10:49,845 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140510209055824 for <Subprocess at 140510219056272 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:10:49,906 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140510209055824 for <Subprocess at 140510219056272 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:10:49,909 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140510209055824 for <Subprocess at 140510219056272 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:10:50,910 INFO success: nginx-unit entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-27 20:10:50,911 INFO success: php-logs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-27 20:11:45,817 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140510209912528 for <Subprocess at 140510197810128 with name php-logs in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:12:12,820 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140510209912528 for <Subprocess at 140510197810128 with name php-logs in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:14,778 INFO Set uid to user 0 succeeded
2023-08-27 20:16:14,780 INFO supervisord started with pid 9
2023-08-27 20:16:15,782 INFO spawned: 'nginx-unit' with pid 10
2023-08-27 20:16:15,784 INFO spawned: 'php-logs' with pid 11
2023-08-27 20:16:15,789 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:15,829 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:15,830 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:15,862 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:15,867 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:15,867 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:15,868 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:15,868 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:15,871 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:15,872 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:15,893 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:15,900 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:15,970 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:15,973 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:16,005 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:16,006 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:16,016 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:16,018 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:16,018 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:16,018 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:16,021 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:16,023 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:17,020 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state STARTING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:17,020 INFO success: nginx-unit entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-27 20:16:17,020 INFO success: php-logs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-27 20:16:17,030 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:17,031 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:17,036 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:17,037 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:17,039 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:17,039 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:17,041 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:17,177 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:16:17,186 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139828399203472 for <Subprocess at 139828395301136 with name nginx-unit in state RUNNING> (stdout)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.11/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|handle_read_event|276] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|record_output|210] [/usr/lib/python3.11/site-packages/supervisor/dispatchers.py|_log|179] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.11/site-packages/supervisor/loggers.py|doRollover|264])
2023-08-27 20:20:19,453 INFO Set uid to user 0 succeeded
2023-08-27 20:20:19,455 INFO supervisord started with pid 8
2023-08-27 20:20:20,459 INFO spawned: 'nginx-unit' with pid 9
2023-08-27 20:20:20,462 INFO spawned: 'php-logs' with pid 10
2023-08-27 20:20:21,877 INFO success: nginx-unit entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-27 20:20:21,878 INFO success: php-logs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
